name: CYNTHIA CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Change directory
        working-directory: ../Capstone202425
        run: ls 

      - name: Build the project
        run: npm run build

      - name: Run tests
        run: npm test
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: npm test
